import pandas as pd

data = {
    'Product': ['Laptop', 'Mouse', 'Keyboard', 'Monitor', 'Laptop', 'Mouse'],
    'Category': ['Electronics', 'Accessory', 'Accessory', 'Electronics', 'Electronics', 'Accessory'],
    'Price': [1200, 25, 75, 300, 1500, 30],
    'Sold': [10, 50, 40, 15, 8, 60]
}

df = pd.DataFrame(data)

# Filtering & Statistics (Easy-Medium)
# Create a new column called Revenue calculated as Price * Sold.
# Filter the DataFrame to show only products where Price is greater than 100.
# Calculate the total Revenue generated by the 'Electronics' category.
# Sort the DataFrame by Price in descending order.
if __name__ == '__main__':
    print("", "\n")

    # Create a new column called Revenue calculated as Price * Sold.
    df['Revenue'] = df['Price'] * df['Sold']
    print(df, "\n")

    # Filter the DataFrame to show only products where Price is greater than 100.
    print(df[df['Price'] > 100], "\n")

    # Calculate the total Revenue generated by the 'Electronics' category.
    total_rev = df[df['Category'] == 'Electronics']['Revenue'].sum()
    print(total_rev, "\n")

    # Sort the DataFrame by Price in descending order.
    print(df.sort_values(by='Price', ascending=False), "\n")
